### PR TITLE
Update release note

### LINKED ISSUE #20: Reverse release notes
Instead of listing release note from older to newer we should to it the other way around newer to older.

this will prevent users to scroll all the way down.

### PR DESCRIPTION
**Pull request by AhyoungRyu**
Fix #20 and [https://github.com/NFLabs/zeppelinhub-documentation/pull/19#issuecomment-233225036](https://github.com/NFLabs/zeppelinhub-documentation/pull/19#issuecomment-233225036).

screen shot 2016-07-18 at 2 36 37 pm

\cc @anthonycorbacho @bzz please review this one :)

### CODE REVIEW

**Comment by bzz** [comment]
Great! 

How does URL to each release look like now?

BTW, is there a reason why we use `<font>` tags everywhere - AFAIK (@felizbear plz correct me if I'm wrong) but it's not even not part of HTML5 spec.

**Comment by AhyoungRyu** [comment]
@bzz Mkdocs render automatically markdown `# (header tag)` as a anchor. So I put `<font>` tag manually.

**Comment by bzz** [comment]
Can you please show examples of the link?

My question was - why `<font>` but not `<div>` or `<span>` ?

AFAIK ['font tag' is deprecated and not supported in HTML5 spec](Obsolete
This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.)

> Obsolete This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

and more from above

> Do not use this element! Though once normalized in HTML 3.2, it was deprecated in HTML 4.01, at the same time as all elements related to styling only, then obsoleted in HTML5.

> Starting with HTML 4, HTML does not convey styling information anymore (outside the <style> element or the style attribute of each element). For any new web development, styling should be written using CSS only.

> The former behavior of the <font> element can be achieved, and even better controlled using the CSS Fonts CSS properties.

**Comment by AhyoungRyu** [comment]
Oh I didn't know that. Let me check again.

**Comment by AhyoungRyu** [comment]
I changed all `<font>` tag to `<span>` tag in every docs pages. Thanks for letting me know :)

**Comment by bzz** [comment]
Great!

This still holds
> Thank you! Can you please show examples of the particular release note link?

**Comment by AhyoungRyu** [comment]
@bzz Oh sorry. Then let me deploy first so that you can go to actual link.

**Comment by bzz** [comment]
Example with local link is ok as well, no need to deploy before merging this one.

**Comment by AhyoungRyu** [comment]
Here is the each actual link
 - [http://help.zeppelinhub.com/release_note/#public-release-3](http://help.zeppelinhub.com/release_note/#public-release-3)
 - [http://help.zeppelinhub.com/release_note/#public-release-2](http://help.zeppelinhub.com/release_note/#public-release-2)
 - [http://help.zeppelinhub.com/release_note/#public-release-1](http://help.zeppelinhub.com/release_note/#public-release-1)
 - [http://help.zeppelinhub.com/release_note/#beta-release](http://help.zeppelinhub.com/release_note/#beta-release)

I also updated screenshot image in the description.

**Comment by bzz** [comment]
Looks great to me! Thank you @AhyoungRyu !

Let's merge then?

**Comment by AhyoungRyu** [comment]
@bzz Thanks for reporting a issue and reviewing this one. I'm merging then :)

**Pull request merged**
