### PR TITLE
Update Documentation and Screenshot

### PR DESCRIPTION
**Pull request by AhyoungRyu**
This PR will update screenshot images (`*.png` and `*.gif`)  and theme in docs site. 

**TODO:**
 - [x] Update some gif images in `Sharing notebooks`, `Creating composers` and `Copying notebooks`
 - [x] Update Zeppelin AD image 
 - [x] Update "Introducing ZeppelinHub" video contents

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
In this PR, I updated the below 3 things.

1. All of the screenshot and gif images. 
2. The header color and Zeppelin AD image.
 - **Before**
before

 - **After**
after

3. ZeppelinHub VideoScribe AD video 
[https://www.youtube.com/watch?v=5HpnXtMDtbw](https://www.youtube.com/watch?v=5HpnXtMDtbw)

**Comment by anthonycorbacho** [comment]
looks good.

lets merge it after the release.

**Comment by AhyoungRyu** [comment]
@anthonycorbacho Okay i will 👯

**Comment by AhyoungRyu** [comment]
@anthonycorbacho Do you want me to deploy this to help.zeppelinhub.com ?

**Comment by anthonycorbacho** [comment]
It is already done doctor zola :)

**Comment by AhyoungRyu** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ @anthonycorbacho Yoohooo 👍

**Pull request merged**
