### PR TITLE
Add release note

### PR DESCRIPTION
**Pull request by AhyoungRyu**
I newly added a **Release Note** for today's ZeppelinHub release.

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
I'm adding screenshots for the quick review :)

1. 

screen shot 2016-04-01 at 12 51 08 pm

2.
screen shot 2016-04-01 at 1 01 35 pm

**Comment by khalidhuseynov** [comment]
thanks for taking care of this @AhyoungRyu! looks really nice, and may need little changes on naming. Basically I was thinking something in chronological order giving the user a prospect on where we are and the history. For example:
```
Beta release - date
features ...

Public release - date
features ...

Updated - date 
features ..
fixes ... 
```

**Comment by AhyoungRyu** [comment]
@khalidhuseynov Thanks for your kind guide ! After addressing them I'll let you know :)

**Comment by AhyoungRyu** [comment]
@khalidhuseynov 
I updated as you suggested yesterday.

- Changed menu name : `Release` -> `Release Note`
- Changed features list to chronological order
- Fixed typo : `form` -> `from`

Here are the screenshots.
screen shot 2016-04-02 at 12 35 54 pm
screen shot 2016-04-02 at 12 36 25 pm

**Comment by khalidhuseynov** [comment]
@AhyoungRyu yes looks good, thanks for changes! one last thing would be to have `Release Notes` on the left-side menu instead of `Release Note`

**Comment by AhyoungRyu** [comment]
Oh that's my bad. I remember you said before. I changed it! 
I'm merging and deploy this one then :)

**Pull request merged**
