### PR TITLE
Update ZeppelinHub integration docs based on Zeppelin version

### PR DESCRIPTION
**Pull request by AhyoungRyu**
Addressed one part of #15  
Two sections in `zeppelin_integration.md` were updated actually. Here is screenshots.

1. Downloading ZIM library 
screen shot 2016-06-06 at 6 57 44 pm

2. Environment variable setting 
screen shot 2016-06-06 at 6 24 42 pm
screen shot 2016-06-06 at 6 24 50 pm

`2016-05-28` is pointing [@khalidhuseynov 's commit](https://github.com/apache/incubator-zeppelin/commit/8cde5c9bd47e3e9682d016274a808e096ab34d0b). 

Maybe this docs will be updated again when `Zeppelin-0.6.0` is released.

### CODE REVIEW

**Comment by AhyoungRyu** [comment]
@khalidhuseynov @bzz Please review this one :)

**Comment by khalidhuseynov** [comment]
thanks @AhyoungRyu for looking into it. some comments:
1. in section 1. what do you think of using `Note: This section is only for Zeppelin 0.5.x users` instead of duplicating version (if consistent with overall docs)? 
2. we may delete part after `Alternatively, ...` to make it shorter (since it's same in zeppelin-site.xml)  and let user to see the [link](https://github.com/apache/incubator-zeppelin/blob/master/docs/storage/storage.md#notebook-storage-in-zeppelinhub--) in zeppelin page by adding something like: 

"You may also find up-to-date instructions on integrating latest Zeppelin master branch with ZeppelinHub  on corresponding [Apache Zeppelin page](https://github.com/apache/incubator-zeppelin/blob/master/docs/storage/storage.md#notebook-storage-in-zeppelinhub--)."

**Comment by AhyoungRyu** [comment]
@khalidhuseynov Thanks for the specific review :)
How about providing real Zeppelin docs link instead of github link ? I mean [https://zeppelin.apache.org/docs/0.6.0-SNAPSHOT/storage/storage.html#ZeppelinHub](https://zeppelin.apache.org/docs/0.6.0-SNAPSHOT/storage/storage.html#ZeppelinHub).

**Comment by khalidhuseynov** [comment]
@AhyoungRyu yeah makes sense, let's provide link to Zeppelin page docs then

**Comment by AhyoungRyu** [comment]
@khalidhuseynov I updated the screenshot images in the PR description. Could you check this one again?

**Comment by khalidhuseynov** [comment]
LGTM, possibly @sejunra @anthonycorbacho @corneadoug @bzz could take a look, follow it, and give some feedback as well.

**Comment by corneadoug** [comment]
The library is also needed for 0.6.0 snapshot before 2016-05-28

**Comment by AhyoungRyu** [comment]
@corneadoug Yeah right I missed that. I updated the screenshot in the PR description. Please take a look at **1. Downloading ZIM library** again.

**Comment by corneadoug** [comment]
LGTM

**Comment by anthonycorbacho** [comment]
LGTM

**Comment by AhyoungRyu** [comment]
@khalidhuseynov @anthonycorbacho @corneadoug Thank you guys. I'm merging this then :)

**Pull request merged**
