### PR TITLE
Update release note

### PR DESCRIPTION
**Pull request by AhyoungRyu**
Here is the screenshot image for the updated release note :)
screen shot 2016-07-15 at 2 09 01 pm

### CODE REVIEW

**Comment by bzz** [comment]
@AhyoungRyu could you please post here link to the live Release Notes that we will be sharing with our users?

**Comment by AhyoungRyu** [comment]
Here is the link [http://help.zeppelinhub.com/release_note/](http://help.zeppelinhub.com/release_note/) :)

**Comment by bzz** [comment]
As we do not have a separate page for each release, could you please add a way to anchor each particular release separately? This way we will be able to share only relevant updates with our users.

Something like  http://help.zeppelinhub.com/release_note#public-release-3

**Comment by AhyoungRyu** [comment]
@bzz Sure. Good suggestion!  I'll make a PR for your comment and #20.

**Pull request merged**
